'use client'

import { motion } from 'framer-motion'
import { Leaf, Recycle, Coins, TrendingUp } from 'lucide-react'
import { AnimatedNumber } from '@/components/ui/AnimatedNumber'
import Link from 'next/link'

const stats = [
  {
    icon: Leaf,
    value: 2847,
    suffix: 't',
    label: 'CO₂ Sequestered',
    description: 'Tons of carbon offset through circular practices',
  },
  {
    icon: Recycle,
    value: 156420,
    suffix: 'kg',
    label: 'Waste Diverted',
    description: 'Kilograms diverted from landfills',
  },
  {
    icon: Coins,
    value: 892340,
    label: 'Eco-Credits Earned',
    description: 'Credits generated by community members',
  },
  {
    icon: TrendingUp,
    value: 94,
    suffix: '%',
    label: 'Recovery Rate',
    description: 'Items successfully routed to sustainable paths',
  },
]

export function Stats() {
  return (
    <section className="py-24 relative overflow-hidden">
      {/* Background glow */}
      <div className="absolute inset-0 bg-gradient-to-b from-eco-glow/5 via-transparent to-transparent" />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-display font-bold text-white mb-4">
            Real Impact, <span className="gradient-text">Real Numbers</span>
          </h2>
          <p className="text-xl text-white/60 max-w-2xl mx-auto">
            Our community is making a measurable difference every day.
          </p>
          <Link href="/impact" className="inline-flex items-center gap-2 mt-4 text-eco-glow hover:text-eco-glow/80 transition-colors">
            View Full Dashboard →
          </Link>
        </motion.div>

        <Link href="/impact" className="block">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 cursor-pointer">
            {stats.map((stat, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="relative group"
              >
                <div className="glass-card p-6 text-center hover-glow hover:scale-[1.02] transition-transform">
                  <div className="inline-flex p-3 rounded-xl bg-eco-card border border-eco-border mb-4">
                    <stat.icon className="w-6 h-6 text-eco-glow" />
                  </div>
                  <div className="text-4xl md:text-5xl font-display font-bold text-white mb-2 glow-text">
                    <AnimatedNumber value={stat.value} suffix={stat.suffix} />
                  </div>
                  <div className="text-lg font-semibold text-white mb-1">{stat.label}</div>
                  <div className="text-sm text-white/50">{stat.description}</div>
                </div>
              </motion.div>
            ))}
          </div>
        </Link>
      </div>
    </section>
  )
}
